// Every user-visible string of the developer console, in both languages. Code samples and identifiers stay untranslated.

const en = {
  title: "Developer API",
  subtitle: "Connect your own systems to your PRIMORA business: read your services, staff, availability and bookings, and receive signed booking events.",
  loading: "Loading your developer settings…",
  loadFailed: "The developer settings could not be loaded.",
  retry: "Try again",
  ownersOnly: "Only the owner of the business can manage API keys and webhooks.",
  tabs: { keys: "Keys", webhooks: "Webhooks", reference: "API reference", limits: "Limits" },
  tabsLabel: "Developer API sections",

  // keys
  keysTitle: "API keys",
  keysIntro: "A key lets a program read this business's data and nothing else. The full key is shown once, when you create it. After that only its first and last characters are kept.",
  keysDisabledTitle: "API keys are not available yet",
  keysDisabledBody: "The platform has not set the maximum requests per minute (api.max_requests_per_minute), so keys cannot be created. Ask the platform administrator to set it.",
  createKey: "Create API key",
  noKeys: "No API keys yet. Create one to connect an integration.",
  keysLoadFailed: "API keys could not be loaded.",
  colName: "Name",
  colKey: "Key",
  colScopes: "Scopes",
  colBranch: "Branch",
  colExpires: "Expires",
  colLastUsed: "Last used",
  colLimit: "Rate limit",
  colStatus: "Status",
  colActions: "Actions",
  allBranches: "All branches",
  never: "Never",
  perMinute: "{n} requests / minute",
  state: { active: "Active", expired: "Expired", revoked: "Revoked" },
  revoke: "Revoke",
  revokeAria: "Revoke key {name}",
  revokeTitle: "Revoke this API key?",
  revokeIntro: "Programs using this key stop working at once. This cannot be undone; create a new key if you need one again.",
  revokeReason: "Why is this key being revoked?",
  revokeConfirm: "Revoke key",
  revoked: "The key was revoked.",
  factKey: "Key",
  factLastUsed: "Last used",
  factScopes: "Scopes",

  // create key dialog
  createKeyTitle: "Create an API key",
  fieldName: "Name",
  fieldNameHint: "What this key is for, for example “Accounting sync”. 3 to 80 characters.",
  fieldBranch: "Branch",
  fieldBranchHint: "Limit the key to one branch, or let it read the whole business.",
  fieldScopes: "Scopes",
  fieldScopesHint: "The key can only do what you tick here.",
  fieldExpiry: "Expires on",
  fieldExpiryHint: "The key stops working at the end of this day (Riyadh time). Latest allowed: {max}.",
  fieldExpiryHintOpen: "The key stops working at the end of this day (Riyadh time).",
  fieldLimit: "Requests per minute",
  fieldLimitHint: "At most {max} requests per minute.",
  scope: {
    "services:read": "Read services",
    "employees:read": "Read staff",
    "availability:read": "Read availability",
    "bookings:read": "Read bookings",
  } as Record<string, string>,
  scopeHelp: {
    "services:read": "Names, prices and durations of your services",
    "employees:read": "Staff names, titles and which services they perform (no phone or email)",
    "availability:read": "Open times for a service on a day",
    "bookings:read": "Booking times, status, service, staff and totals (no customer details)",
  } as Record<string, string>,
  cancel: "Cancel",
  create: "Create key",
  creating: "Creating…",
  needName: "Enter a name of 3 to 80 characters.",
  needScope: "Tick at least one scope.",
  needExpiry: "Choose an expiry date.",
  needLimit: "Enter a whole number of requests per minute from 1 to {max}.",

  // show once
  keyCreatedTitle: "Your new API key",
  keyCreatedWarning: "Copy this key now. It is shown only once and cannot be recovered. If you lose it, revoke it and create another.",
  copy: "Copy",
  copied: "Copied to the clipboard.",
  copyFailed: "Copying was blocked by the browser. Select the key and copy it by hand.",
  storedAck: "I have copied the key and stored it somewhere safe.",
  done: "Done",
  secretCreatedTitle: "Your webhook signing secret",
  secretCreatedWarning: "Copy this secret now. It is shown only once. Your server uses it to check that a delivery really came from PRIMORA.",
  secretRotatedTitle: "Your new signing secret",
  secretLabel: "Signing secret",
  keyLabel: "API key",

  // webhooks
  webhooksTitle: "Webhook endpoints",
  webhooksIntro: "PRIMORA sends a signed HTTPS request to each endpoint when a booking is created, confirmed, cancelled or completed. Deliveries are retried and every event has a stable id you can de-duplicate on.",
  deliveryOffTitle: "Webhook delivery is switched off",
  deliveryOffBody: "The platform has not set the delivery settings ({missing}), so no events are sent and none are queued. You can still register endpoints.",
  addEndpoint: "Add endpoint",
  noEndpoints: "No webhook endpoints yet.",
  endpointsLoadFailed: "Webhook endpoints could not be loaded.",
  colUrl: "Address",
  colEvents: "Events",
  colDelivery: "Delivery",
  endpointState: { ok: "Delivering", paused: "Paused", failing: "Disabled after failures", retired: "Retired", idle: "No deliveries yet" },
  lastSuccess: "Last success {when}",
  lastFailure: "Last failure {when}",
  failureStreak: "{n} failed attempts in a row",
  pause: "Pause",
  resume: "Resume",
  rotate: "New secret",
  edit: "Edit",
  remove: "Delete",
  viewLog: "Delivery log",
  endpointAria: "{action} endpoint {name}",
  addEndpointTitle: "Add a webhook endpoint",
  fieldUrl: "Address",
  fieldUrlHint: "An https:// address on a public domain name, on the standard port. IP addresses, localhost and internal names are refused.",
  fieldEvents: "Events",
  eventHelp: {
    "booking.created": "A booking was made",
    "booking.confirmed": "A booking was confirmed (paid or accepted)",
    "booking.cancelled": "A booking was cancelled",
    "booking.completed": "A booking was completed",
  } as Record<string, string>,
  needUrl: "Enter an https:// address.",
  needEvent: "Tick at least one event.",
  urlProblem: {
    malformed: "This is not a valid address.",
    too_long: "This address is too long.",
    not_https: "Only https:// addresses are accepted.",
    credentials: "Remove the user name and password from the address.",
    port: "Use the standard HTTPS port (443).",
    ip_literal: "Use a domain name, not an IP address.",
    single_label: "Use a full domain name such as hooks.example.com.",
    local_host: "This name is for internal use and cannot be reached from the internet.",
  } as Record<string, string>,
  editEndpointTitle: "Edit endpoint",
  save: "Save",
  saving: "Saving…",
  pauseTitle: "Pause this endpoint?",
  pauseIntro: "It stops receiving events and anything still waiting for it is dropped. You can resume it later.",
  pauseReason: "Why is it being paused?",
  resumeTitle: "Resume this endpoint?",
  resumeIntro: "It receives new events again. Events missed while it was paused are not sent.",
  resumeReason: "Why is it being resumed?",
  rotateTitle: "Create a new signing secret?",
  rotateIntro: "The current secret stops working immediately. Update your server with the new secret straight away.",
  rotateReason: "Why is the secret being replaced?",
  deleteTitle: "Delete this endpoint?",
  deleteIntro: "It stops receiving events and its secret is destroyed. Its delivery history is kept.",
  deleteReason: "Why is it being deleted?",
  paused: "The endpoint was paused.",
  resumed: "The endpoint was resumed.",
  deleted: "The endpoint was deleted.",
  endpointSaved: "The endpoint was saved.",

  // delivery log
  logTitle: "Delivery log",
  logIntro: "The most recent events queued for your endpoints. Only booking facts are sent: never a customer's name, phone, email or notes.",
  logFor: "Showing endpoint {name}.",
  logAll: "Showing all endpoints.",
  showAll: "Show all endpoints",
  noDeliveries: "No deliveries yet.",
  deliveriesLoadFailed: "The delivery log could not be loaded.",
  colEvent: "Event",
  colWhen: "Queued",
  colAttempts: "Attempts",
  colResult: "Result",
  colNext: "Next attempt",
  deliveryState: { pending: "Waiting", delivered: "Delivered", failed: "Failed", skipped: "Skipped" },
  httpStatus: "HTTP {n}",
  retryDelivery: "Retry",
  retryAria: "Retry delivery of {event}",
  retryTitle: "Send this event again?",
  retryIntro: "The event goes back in the queue with a fresh set of attempts.",
  retryReason: "Why is it being sent again?",
  retried: "The event was queued again.",
  loadMore: "Show more",
  loadingMore: "Loading…",

  // limits
  limitsTitle: "Limits and settings",
  limitsIntro: "These values are set by the platform. A value that is not set switches the feature it controls off rather than guessing a number.",
  limitsPlatform: "Set by the platform",
  limitsContract: "Fixed by the API contract",
  notSet: "Not set",
  settingLabel: {
    "api.max_requests_per_minute": "Highest requests per minute for a key",
    "api.max_key_lifetime_days": "Longest life of a key (days)",
    "api.webhook_max_attempts": "Delivery attempts per event",
    "api.webhook_retry_base_seconds": "Retry delay base (seconds)",
    "api.webhook_disable_after_failures": "Failed attempts in a row before an endpoint is disabled",
  } as Record<string, string>,
  settingUnset: {
    "api.max_requests_per_minute": "Keys cannot be created.",
    "api.max_key_lifetime_days": "Any future expiry date is accepted.",
    "api.webhook_max_attempts": "No webhook deliveries are queued or sent.",
    "api.webhook_retry_base_seconds": "No webhook deliveries are queued or sent.",
    "api.webhook_disable_after_failures": "Endpoints are never disabled automatically.",
  } as Record<string, string>,
  contractRows: {
    pageDefault: "Items per page by default",
    pageMax: "Most items per page",
    window: "Rate-limit window (seconds)",
    tolerance: "Signature timestamp tolerance (seconds)",
    timeout: "Time an endpoint has to answer (seconds)",
    backoff: "Retry delay never exceeds (hours)",
    lease: "A delivery being sent is not offered again for (minutes)",
    url: "Longest webhook address (characters)",
  },

  // errors
  errNotConfigured: "This is not available yet because the platform has not set the required limit.",
  errDuplicateKey: "A key with this name already exists. Choose another name.",
  errDuplicateUrl: "This address is already registered for your business.",
  errNotFound: "That item no longer exists.",
  errForbidden: "You do not have access to do this.",
  errSignIn: "Sign in again to continue.",

  // reference
  refTitle: "API reference",
  refIntro: "A read-only HTTPS API. Every request carries your key; there is no browser access, so call it from your own server.",
  refBase: "Base address",
  refBaseUnset: "your project's functions address",
  refAuth: "Authentication",
  refAuthBody: "Send the key in the Authorization header as a bearer token. Never put it in a web page or a mobile app, and never in a URL.",
  refEndpoints: "Endpoints",
  refScopeNeeded: "Scope",
  refParams: "Parameters",
  refExample: "Example request",
  refResponse: "Response",
  refListNote: "Lists return { data, pagination } where pagination is { limit, has_more, next_cursor }. Pass next_cursor back as the cursor parameter to read the next page; the cursor is opaque and must not be edited.",
  refDates: "Dates without a time (2026-10-07) are calendar days in Riyadh (Asia/Riyadh). from is inclusive and to is exclusive. A timestamp must state its offset, such as 2026-10-07T09:30:00+03:00. All amounts are in SAR.",
  refErrors: "Errors",
  refErrorsBody: "Every error has the same shape, and the request id is also sent in the X-Request-Id header. Quote it when you contact support.",
  refStatuses: "Status codes",
  refStatusRows: [
    ["400", "invalid_request", "A parameter is missing, unknown, repeated or malformed."],
    ["401", "unauthorized", "The key is missing, unknown, revoked or expired (the answer never says which)."],
    ["403", "forbidden", "The key does not have the scope this endpoint needs."],
    ["404", "not_found", "No such endpoint or resource."],
    ["405", "method_not_allowed", "Only GET is accepted."],
    ["429", "rate_limited", "The key used up its requests for this minute. Wait for Retry-After seconds."],
    ["500", "internal_error", "Something went wrong on our side."],
  ] as string[][],
  refRate: "Rate limits",
  refRateBody: "Every authenticated answer carries X-RateLimit-Limit, X-RateLimit-Remaining and X-RateLimit-Reset (Unix time when the minute ends). A 429 also carries Retry-After.",
  refWebhooks: "Webhooks",
  refWebhooksBody: "Each event is an HTTPS POST with a JSON body. Answer with any 2xx status within {n} seconds; anything else is retried with growing delays until the platform's attempt limit. Redirects are not followed. The same event id always means the same event: de-duplicate on it.",
  refEvents: "Events",
  refPayload: "Example event",
  refSignature: "Checking the signature",
  refSignatureBody: "Every delivery has an X-Primora-Signature header, t=<unix time>,v1=<hex>. v1 is the HMAC-SHA256, with your signing secret as the key, of the timestamp, a dot, and the exact request body. Verify against the raw body before parsing it, reject timestamps older than {n} seconds, and compare in constant time.",
  refPrivacy: "What is never sent",
  refPrivacyBody: "Customer names, phone numbers, email addresses, notes, addresses and payment details are not available through the API or in webhooks.",
  copyCode: "Copy code",
};

export type DeveloperCopy = typeof en;

const ar: DeveloperCopy = {
  title: "واجهة المطورين",
  subtitle: "اربط أنظمتك بنشاطك في PRIMORA: اقرأ خدماتك وموظفيك والمواعيد المتاحة وحجوزاتك، واستقبل أحداث الحجز الموقّعة.",
  loading: "جارٍ تحميل إعدادات المطورين…",
  loadFailed: "تعذر تحميل إعدادات المطورين.",
  retry: "إعادة المحاولة",
  ownersOnly: "مالك النشاط وحده يدير مفاتيح الواجهة وخطافات الويب.",
  tabs: { keys: "المفاتيح", webhooks: "خطافات الويب", reference: "مرجع الواجهة", limits: "الحدود" },
  tabsLabel: "أقسام واجهة المطورين",

  keysTitle: "مفاتيح الواجهة",
  keysIntro: "المفتاح يتيح لبرنامج قراءة بيانات هذا النشاط فقط. يظهر المفتاح كاملاً مرة واحدة عند إنشائه، وبعدها يُحفظ أوله وآخره فقط.",
  keysDisabledTitle: "مفاتيح الواجهة غير متاحة بعد",
  keysDisabledBody: "لم تحدد المنصة الحد الأقصى للطلبات في الدقيقة (api.max_requests_per_minute)، لذلك لا يمكن إنشاء مفاتيح. اطلب من مسؤول المنصة تحديده.",
  createKey: "إنشاء مفتاح",
  noKeys: "لا توجد مفاتيح بعد. أنشئ مفتاحاً لربط أحد أنظمتك.",
  keysLoadFailed: "تعذر تحميل المفاتيح.",
  colName: "الاسم",
  colKey: "المفتاح",
  colScopes: "الصلاحيات",
  colBranch: "الفرع",
  colExpires: "ينتهي",
  colLastUsed: "آخر استخدام",
  colLimit: "حد الطلبات",
  colStatus: "الحالة",
  colActions: "إجراءات",
  allBranches: "كل الفروع",
  never: "لم يُستخدم",
  perMinute: "{n} طلب في الدقيقة",
  state: { active: "نشط", expired: "منتهي", revoked: "ملغى" },
  revoke: "إلغاء",
  revokeAria: "إلغاء المفتاح {name}",
  revokeTitle: "إلغاء مفتاح الواجهة؟",
  revokeIntro: "تتوقف البرامج التي تستخدم هذا المفتاح فوراً. لا يمكن التراجع؛ أنشئ مفتاحاً جديداً إن احتجت إليه.",
  revokeReason: "ما سبب إلغاء المفتاح؟",
  revokeConfirm: "إلغاء المفتاح",
  revoked: "تم إلغاء المفتاح.",
  factKey: "المفتاح",
  factLastUsed: "آخر استخدام",
  factScopes: "الصلاحيات",

  createKeyTitle: "إنشاء مفتاح واجهة",
  fieldName: "الاسم",
  fieldNameHint: "الغرض من المفتاح، مثل «مزامنة المحاسبة». من 3 إلى 80 حرفاً.",
  fieldBranch: "الفرع",
  fieldBranchHint: "اجعل المفتاح خاصاً بفرع واحد أو دعه يقرأ النشاط كله.",
  fieldScopes: "الصلاحيات",
  fieldScopesHint: "لا يستطيع المفتاح سوى ما تحدده هنا.",
  fieldExpiry: "تاريخ الانتهاء",
  fieldExpiryHint: "يتوقف المفتاح عن العمل في نهاية هذا اليوم (بتوقيت الرياض). أبعد تاريخ مسموح: {max}.",
  fieldExpiryHintOpen: "يتوقف المفتاح عن العمل في نهاية هذا اليوم (بتوقيت الرياض).",
  fieldLimit: "الطلبات في الدقيقة",
  fieldLimitHint: "بحد أقصى {max} طلب في الدقيقة.",
  scope: {
    "services:read": "قراءة الخدمات",
    "employees:read": "قراءة الموظفين",
    "availability:read": "قراءة المواعيد المتاحة",
    "bookings:read": "قراءة الحجوزات",
  },
  scopeHelp: {
    "services:read": "أسماء خدماتك وأسعارها ومددها",
    "employees:read": "أسماء الموظفين وألقابهم والخدمات التي يقدمونها (دون هاتف أو بريد)",
    "availability:read": "الأوقات المتاحة لخدمة في يوم معين",
    "bookings:read": "أوقات الحجوزات وحالتها والخدمة والموظف والإجماليات (دون بيانات العميل)",
  },
  cancel: "إلغاء",
  create: "إنشاء المفتاح",
  creating: "جارٍ الإنشاء…",
  needName: "اكتب اسماً من 3 إلى 80 حرفاً.",
  needScope: "حدد صلاحية واحدة على الأقل.",
  needExpiry: "اختر تاريخ الانتهاء.",
  needLimit: "اكتب عدداً صحيحاً للطلبات في الدقيقة من 1 إلى {max}.",

  keyCreatedTitle: "مفتاح الواجهة الجديد",
  keyCreatedWarning: "انسخ المفتاح الآن. يظهر مرة واحدة فقط ولا يمكن استرجاعه. إن فقدته فألغِه وأنشئ غيره.",
  copy: "نسخ",
  copied: "تم النسخ إلى الحافظة.",
  copyFailed: "منع المتصفح النسخ. حدد المفتاح وانسخه يدوياً.",
  storedAck: "نسخت المفتاح وحفظته في مكان آمن.",
  done: "تم",
  secretCreatedTitle: "سر توقيع خطاف الويب",
  secretCreatedWarning: "انسخ السر الآن. يظهر مرة واحدة فقط. يستخدمه خادمك للتأكد أن الإرسال جاء فعلاً من PRIMORA.",
  secretRotatedTitle: "سر التوقيع الجديد",
  secretLabel: "سر التوقيع",
  keyLabel: "مفتاح الواجهة",

  webhooksTitle: "نقاط استقبال خطافات الويب",
  webhooksIntro: "ترسل PRIMORA طلب HTTPS موقّعاً إلى كل نقطة عند إنشاء حجز أو تأكيده أو إلغائه أو إكماله. تُعاد المحاولة عند الفشل ولكل حدث معرّف ثابت يمكنك منع تكراره به.",
  deliveryOffTitle: "إرسال خطافات الويب متوقف",
  deliveryOffBody: "لم تحدد المنصة إعدادات الإرسال ({missing})، لذلك لا تُرسل أحداث ولا تُوضع في الانتظار. يمكنك مع ذلك تسجيل النقاط.",
  addEndpoint: "إضافة نقطة",
  noEndpoints: "لا توجد نقاط استقبال بعد.",
  endpointsLoadFailed: "تعذر تحميل نقاط الاستقبال.",
  colUrl: "العنوان",
  colEvents: "الأحداث",
  colDelivery: "الإرسال",
  endpointState: { ok: "يعمل", paused: "متوقف مؤقتاً", failing: "عُطّل بعد إخفاقات", retired: "مُنهى", idle: "لا إرسال بعد" },
  lastSuccess: "آخر نجاح {when}",
  lastFailure: "آخر إخفاق {when}",
  failureStreak: "{n} محاولات فاشلة متتالية",
  pause: "إيقاف مؤقت",
  resume: "استئناف",
  rotate: "سر جديد",
  edit: "تعديل",
  remove: "حذف",
  viewLog: "سجل الإرسال",
  endpointAria: "{action} النقطة {name}",
  addEndpointTitle: "إضافة نقطة استقبال",
  fieldUrl: "العنوان",
  fieldUrlHint: "عنوان https:// على اسم نطاق عام وبالمنفذ القياسي. تُرفض عناوين IP وlocalhost والأسماء الداخلية.",
  fieldEvents: "الأحداث",
  eventHelp: {
    "booking.created": "تم إنشاء حجز",
    "booking.confirmed": "تم تأكيد حجز (دُفع أو قُبل)",
    "booking.cancelled": "تم إلغاء حجز",
    "booking.completed": "تم إكمال حجز",
  },
  needUrl: "اكتب عنوان https://.",
  needEvent: "حدد حدثاً واحداً على الأقل.",
  urlProblem: {
    malformed: "هذا العنوان غير صالح.",
    too_long: "العنوان أطول من المسموح.",
    not_https: "تُقبل عناوين https:// فقط.",
    credentials: "احذف اسم المستخدم وكلمة المرور من العنوان.",
    port: "استخدم منفذ HTTPS القياسي (443).",
    ip_literal: "استخدم اسم نطاق بدل عنوان IP.",
    single_label: "استخدم اسم نطاق كاملاً مثل hooks.example.com.",
    local_host: "هذا الاسم للاستخدام الداخلي ولا يمكن الوصول إليه من الإنترنت.",
  },
  editEndpointTitle: "تعديل النقطة",
  save: "حفظ",
  saving: "جارٍ الحفظ…",
  pauseTitle: "إيقاف هذه النقطة مؤقتاً؟",
  pauseIntro: "تتوقف عن استقبال الأحداث ويُسقَط كل ما ينتظر إرساله إليها. يمكنك استئنافها لاحقاً.",
  pauseReason: "ما سبب الإيقاف؟",
  resumeTitle: "استئناف هذه النقطة؟",
  resumeIntro: "تستقبل الأحداث الجديدة من جديد. لا تُرسل الأحداث التي فاتتها أثناء التوقف.",
  resumeReason: "ما سبب الاستئناف؟",
  rotateTitle: "إنشاء سر توقيع جديد؟",
  rotateIntro: "يتوقف السر الحالي عن العمل فوراً. حدّث خادمك بالسر الجديد مباشرة.",
  rotateReason: "ما سبب استبدال السر؟",
  deleteTitle: "حذف هذه النقطة؟",
  deleteIntro: "تتوقف عن استقبال الأحداث ويُتلَف سرها. يبقى سجل إرسالها محفوظاً.",
  deleteReason: "ما سبب الحذف؟",
  paused: "تم إيقاف النقطة مؤقتاً.",
  resumed: "تم استئناف النقطة.",
  deleted: "تم حذف النقطة.",
  endpointSaved: "تم حفظ النقطة.",

  logTitle: "سجل الإرسال",
  logIntro: "أحدث الأحداث الموضوعة في الانتظار لنقاطك. تُرسل وقائع الحجز فقط: لا اسم عميل ولا هاتف ولا بريد ولا ملاحظات.",
  logFor: "عرض النقطة {name}.",
  logAll: "عرض كل النقاط.",
  showAll: "عرض كل النقاط",
  noDeliveries: "لا توجد عمليات إرسال بعد.",
  deliveriesLoadFailed: "تعذر تحميل سجل الإرسال.",
  colEvent: "الحدث",
  colWhen: "وقت الإضافة",
  colAttempts: "المحاولات",
  colResult: "النتيجة",
  colNext: "المحاولة التالية",
  deliveryState: { pending: "في الانتظار", delivered: "تم التسليم", failed: "فشل", skipped: "تم التخطي" },
  httpStatus: "HTTP {n}",
  retryDelivery: "إعادة الإرسال",
  retryAria: "إعادة إرسال الحدث {event}",
  retryTitle: "إرسال هذا الحدث مرة أخرى؟",
  retryIntro: "يعود الحدث إلى الانتظار بمحاولات جديدة.",
  retryReason: "ما سبب إعادة الإرسال؟",
  retried: "أُعيد الحدث إلى الانتظار.",
  loadMore: "عرض المزيد",
  loadingMore: "جارٍ التحميل…",

  limitsTitle: "الحدود والإعدادات",
  limitsIntro: "تحدد المنصة هذه القيم. القيمة غير المحددة توقف الميزة المرتبطة بها بدل تخمين رقم.",
  limitsPlatform: "تحددها المنصة",
  limitsContract: "ثابتة في عقد الواجهة",
  notSet: "غير محدد",
  settingLabel: {
    "api.max_requests_per_minute": "أعلى عدد طلبات في الدقيقة للمفتاح",
    "api.max_key_lifetime_days": "أطول عمر للمفتاح (أيام)",
    "api.webhook_max_attempts": "محاولات الإرسال لكل حدث",
    "api.webhook_retry_base_seconds": "أساس مهلة إعادة المحاولة (ثوانٍ)",
    "api.webhook_disable_after_failures": "محاولات فاشلة متتالية قبل تعطيل النقطة",
  },
  settingUnset: {
    "api.max_requests_per_minute": "لا يمكن إنشاء مفاتيح.",
    "api.max_key_lifetime_days": "يُقبل أي تاريخ انتهاء مستقبلي.",
    "api.webhook_max_attempts": "لا تُوضع خطافات ويب في الانتظار ولا تُرسل.",
    "api.webhook_retry_base_seconds": "لا تُوضع خطافات ويب في الانتظار ولا تُرسل.",
    "api.webhook_disable_after_failures": "لا تُعطَّل النقاط تلقائياً.",
  },
  contractRows: {
    pageDefault: "عدد العناصر في الصفحة افتراضياً",
    pageMax: "أكبر عدد عناصر في الصفحة",
    window: "نافذة حد الطلبات (ثوانٍ)",
    tolerance: "سماحية توقيت التوقيع (ثوانٍ)",
    timeout: "مهلة رد النقطة (ثوانٍ)",
    backoff: "لا تتجاوز مهلة إعادة المحاولة (ساعات)",
    lease: "لا يُعرض الحدث قيد الإرسال مجدداً قبل (دقائق)",
    url: "أطول عنوان لخطاف الويب (حرفاً)",
  },

  errNotConfigured: "هذه الميزة غير متاحة بعد لأن المنصة لم تحدد الحد المطلوب.",
  errDuplicateKey: "يوجد مفتاح بهذا الاسم. اختر اسماً آخر.",
  errDuplicateUrl: "هذا العنوان مسجل لنشاطك مسبقاً.",
  errNotFound: "لم يعد هذا العنصر موجوداً.",
  errForbidden: "ليست لديك صلاحية لتنفيذ هذا.",
  errSignIn: "سجّل الدخول من جديد للمتابعة.",

  refTitle: "مرجع الواجهة",
  refIntro: "واجهة HTTPS للقراءة فقط. يحمل كل طلب مفتاحك، ولا يوجد وصول من المتصفح، فاستدعِها من خادمك.",
  refBase: "العنوان الأساسي",
  refBaseUnset: "عنوان دوال مشروعك",
  refAuth: "المصادقة",
  refAuthBody: "أرسل المفتاح في ترويسة Authorization بصيغة Bearer. لا تضعه في صفحة ويب أو تطبيق جوال ولا في الرابط.",
  refEndpoints: "نقاط الوصول",
  refScopeNeeded: "الصلاحية",
  refParams: "المعاملات",
  refExample: "مثال على طلب",
  refResponse: "الاستجابة",
  refListNote: "تعيد القوائم { data, pagination } حيث pagination هي { limit, has_more, next_cursor }. مرّر next_cursor كمعامل cursor لقراءة الصفحة التالية؛ المؤشر مبهم ولا يجوز تعديله.",
  refDates: "التاريخ دون وقت (2026-10-07) يعني يوماً بتقويم الرياض (Asia/Riyadh). from شاملة وto غير شاملة. يجب أن يذكر الطابع الزمني فارقه مثل 2026-10-07T09:30:00+03:00. كل المبالغ بالريال السعودي.",
  refErrors: "الأخطاء",
  refErrorsBody: "لكل خطأ الشكل نفسه، ويُرسل معرّف الطلب أيضاً في ترويسة X-Request-Id. اذكره عند التواصل مع الدعم.",
  refStatuses: "رموز الحالة",
  refStatusRows: [
    ["400", "invalid_request", "معامل ناقص أو غير معروف أو مكرر أو بصيغة خاطئة."],
    ["401", "unauthorized", "المفتاح مفقود أو غير معروف أو ملغى أو منتهٍ (لا يذكر الرد أيها)."],
    ["403", "forbidden", "ليس للمفتاح الصلاحية التي تحتاجها هذه النقطة."],
    ["404", "not_found", "لا توجد نقطة أو مورد بهذا الاسم."],
    ["405", "method_not_allowed", "يُقبل GET فقط."],
    ["429", "rate_limited", "استنفد المفتاح طلبات هذه الدقيقة. انتظر عدد الثواني في Retry-After."],
    ["500", "internal_error", "حدث خطأ من جانبنا."],
  ],
  refRate: "حدود الطلبات",
  refRateBody: "يحمل كل رد موثّق X-RateLimit-Limit وX-RateLimit-Remaining وX-RateLimit-Reset (وقت يونكس لانتهاء الدقيقة). ويحمل رد 429 أيضاً Retry-After.",
  refWebhooks: "خطافات الويب",
  refWebhooksBody: "كل حدث طلب HTTPS POST بجسم JSON. أجب بأي حالة 2xx خلال {n} ثوانٍ؛ غير ذلك يُعاد بمهل متزايدة حتى حد المحاولات الذي تحدده المنصة. لا تُتبع إعادة التوجيه. المعرّف نفسه يعني الحدث نفسه: امنع التكرار به.",
  refEvents: "الأحداث",
  refPayload: "مثال على حدث",
  refSignature: "التحقق من التوقيع",
  refSignatureBody: "لكل إرسال ترويسة X-Primora-Signature بالصيغة t=<وقت يونكس>,v1=<hex>. القيمة v1 هي HMAC-SHA256 بسر التوقيع كمفتاح للطابع الزمني ثم نقطة ثم جسم الطلب كما وصل تماماً. تحقق على الجسم الخام قبل تحليله، وارفض الطوابع الأقدم من {n} ثانية، وقارن بزمن ثابت.",
  refPrivacy: "ما لا يُرسل أبداً",
  refPrivacyBody: "أسماء العملاء وأرقام هواتفهم وبريدهم وملاحظاتهم وعناوينهم وبيانات الدفع غير متاحة عبر الواجهة ولا في خطافات الويب.",
  copyCode: "نسخ الشيفرة",
};

export const developerCopy: Record<"en" | "ar", DeveloperCopy> = { en, ar };
