-- Migration: 20261006093000_webhook_endpoints.sql
-- G69 "Real developer API", part 2: signed, retried, idempotent booking webhooks.
--
-- public.webhook_subscriptions is reused and hardened. Before this migration a developer inserted rows from the
-- browser, chose the signing secret there, and read it back with every select. Now:
--   * endpoints belong to a provider (not to a developer profile) and are written only by commands that the
--     provider owner can run; clients have no INSERT/UPDATE/DELETE and no way to read a secret;
--   * the signing secret is generated by the database, returned once, and kept in webhook_subscription_secrets, a
--     table no client role can read, so only the service-role delivery function can sign;
--   * addresses must be https on a public host name (webhook_url_rejection; the delivery function re-checks the
--     resolved addresses and never follows redirects);
--   * additive AFTER triggers on public.bookings enqueue one delivery per endpoint and event, with a stable event id
--     per booking and event type, so a replay cannot produce a second delivery;
--   * delivery is a small state machine in webhook_deliveries (attempt count, next attempt, last status), gated by
--     platform settings that are unset until the owner sets them.
-- Legacy rows (created by the old page, with browser-chosen secrets) are switched off and lose their secret column.

-- ---------------------------------------------------------------------------
-- 1. Hardened webhook_subscriptions
-- ---------------------------------------------------------------------------
ALTER TABLE public.webhook_subscriptions ALTER COLUMN developer_profile_id DROP NOT NULL;
ALTER TABLE public.webhook_subscriptions
  ADD COLUMN IF NOT EXISTS provider_id UUID REFERENCES public.providers(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS branch_id UUID REFERENCES public.branches(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS consecutive_failures INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS disabled_reason TEXT,
  ADD COLUMN IF NOT EXISTS disabled_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_attempt_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_success_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_failure_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

-- BEGIN legacy-webhook-retirement
-- Rows made by the old page carry a secret chosen in the browser and have no provider to deliver for: switch them
-- off, keep them as history, and remove the plaintext secret column for good.
UPDATE public.webhook_subscriptions
   SET is_active = FALSE, disabled_reason = 'retired', disabled_at = COALESCE(disabled_at, now()),
       event_types = ARRAY(SELECT e FROM unnest(event_types) e
                            WHERE e IN ('booking.created', 'booking.confirmed', 'booking.cancelled', 'booking.completed'))
 WHERE provider_id IS NULL;
ALTER TABLE public.webhook_subscriptions DROP COLUMN IF EXISTS secret_key;
-- END legacy-webhook-retirement

-- Only the four booking events can be subscribed to. Further rules (https address, non-empty events) are enforced by
-- the commands: clients have no write privilege on this table.
ALTER TABLE public.webhook_subscriptions DROP CONSTRAINT IF EXISTS webhook_subscriptions_known_events;
ALTER TABLE public.webhook_subscriptions ADD CONSTRAINT webhook_subscriptions_known_events
  CHECK (event_types <@ ARRAY['booking.created', 'booking.confirmed', 'booking.cancelled', 'booking.completed']::TEXT[]);
ALTER TABLE public.webhook_subscriptions DROP CONSTRAINT IF EXISTS webhook_subscriptions_owned_or_retired;
ALTER TABLE public.webhook_subscriptions ADD CONSTRAINT webhook_subscriptions_owned_or_retired
  CHECK (provider_id IS NOT NULL OR is_active = FALSE);
CREATE UNIQUE INDEX IF NOT EXISTS uq_webhook_subscriptions_url
  ON public.webhook_subscriptions (provider_id, lower(target_url)) WHERE provider_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_webhook_subscriptions_provider ON public.webhook_subscriptions (provider_id) WHERE deleted_at IS NULL;

-- The signing secret. No client grant, no policy: only the service role and the commands below reach it.
CREATE TABLE IF NOT EXISTS public.webhook_subscription_secrets (
  subscription_id UUID PRIMARY KEY REFERENCES public.webhook_subscriptions(id) ON DELETE CASCADE,
  signing_secret TEXT NOT NULL CHECK (signing_secret ~ '^whsec_[0-9a-f]{64}$'),
  rotated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.webhook_deliveries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  subscription_id UUID NOT NULL REFERENCES public.webhook_subscriptions(id) ON DELETE CASCADE,
  provider_id UUID NOT NULL REFERENCES public.providers(id) ON DELETE CASCADE,
  booking_id UUID NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE,
  event_id UUID NOT NULL,
  event_type TEXT NOT NULL,
  payload JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'delivered', 'failed', 'skipped')),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_attempt_at TIMESTAMPTZ,
  last_status_code INTEGER,
  last_error TEXT,
  delivered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (subscription_id, event_id)
);
COMMENT ON TABLE public.webhook_deliveries IS
  'One row per endpoint and event. payload holds booking facts only (no customer name, phone, email or notes).';
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_due ON public.webhook_deliveries (next_attempt_at) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_endpoint ON public.webhook_deliveries (subscription_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_booking ON public.webhook_deliveries (booking_id);

ALTER TABLE public.webhook_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_subscription_secrets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_deliveries ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.webhook_subscriptions, public.webhook_subscription_secrets, public.webhook_deliveries FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.webhook_subscriptions, public.webhook_deliveries TO authenticated;
GRANT ALL ON public.webhook_subscriptions, public.webhook_subscription_secrets, public.webhook_deliveries TO service_role;

DROP POLICY IF EXISTS "Developers manage own webhook subscriptions" ON public.webhook_subscriptions;
DROP POLICY IF EXISTS "Owners and administrators read webhook endpoints" ON public.webhook_subscriptions;
CREATE POLICY "Owners and administrators read webhook endpoints" ON public.webhook_subscriptions
  FOR SELECT TO authenticated
  USING (public.is_admin() OR (deleted_at IS NULL AND EXISTS (
    SELECT 1 FROM public.providers p WHERE p.id = webhook_subscriptions.provider_id AND p.owner_id = auth.uid()
  )));

DROP POLICY IF EXISTS "Owners and administrators read webhook deliveries" ON public.webhook_deliveries;
CREATE POLICY "Owners and administrators read webhook deliveries" ON public.webhook_deliveries
  FOR SELECT TO authenticated
  USING (public.is_admin() OR EXISTS (
    SELECT 1 FROM public.providers p WHERE p.id = webhook_deliveries.provider_id AND p.owner_id = auth.uid()
  ));

-- ---------------------------------------------------------------------------
-- 2. Address policy (mirrors webhook-url.ts; supabase/tests/fixtures/webhook-url-vectors.json keeps them in step)
-- ---------------------------------------------------------------------------
-- Returns NULL when the address is acceptable, otherwise the reason. Stricter than the TypeScript version in a few
-- exotic spellings (any backslash, any non-ASCII host): this is the gate that stores an endpoint.
CREATE OR REPLACE FUNCTION public.webhook_url_rejection(p_url TEXT)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  v_rest TEXT;
  v_authority TEXT;
  v_host TEXT;
  v_port TEXT;
  v_last TEXT;
  v_suffix TEXT;
BEGIN
  IF p_url IS NULL OR p_url = '' OR p_url <> btrim(p_url) THEN RETURN 'malformed'; END IF;
  IF char_length(p_url) > 2048 THEN RETURN 'too_long'; END IF;
  IF p_url ~ '[[:space:][:cntrl:]\\]' THEN RETURN 'malformed'; END IF;
  IF p_url !~* '^[a-z][a-z0-9+.-]*:' THEN RETURN 'malformed'; END IF;
  IF p_url !~* '^https:' THEN RETURN 'not_https'; END IF;
  IF p_url !~* '^https://' THEN RETURN 'malformed'; END IF;

  v_rest := substr(p_url, 9);
  v_authority := substring(v_rest FROM '^[^/?#]*');
  IF v_authority = '' THEN RETURN 'malformed'; END IF;
  IF position('@' IN v_authority) > 0 THEN RETURN 'credentials'; END IF;
  IF left(v_authority, 1) = '[' THEN RETURN 'ip_literal'; END IF;

  IF position(':' IN v_authority) > 0 THEN
    IF v_authority !~ '^[^:]+:[0-9]*$' THEN RETURN 'malformed'; END IF;
    v_host := split_part(v_authority, ':', 1);
    v_port := split_part(v_authority, ':', 2);
    IF v_port <> '' AND v_port <> '443' THEN RETURN 'port'; END IF;
  ELSE
    v_host := v_authority;
  END IF;

  v_host := lower(v_host);
  IF right(v_host, 1) = '.' THEN v_host := left(v_host, -1); END IF;
  IF v_host = '' OR v_host !~ '^[a-z0-9.-]+$' OR v_host ~ '(^\.|\.\.)' THEN RETURN 'malformed'; END IF;
  IF v_host ~ '^[0-9.]+$' THEN RETURN 'ip_literal'; END IF;
  v_last := substring(v_host FROM '[^.]+$');
  IF v_last ~ '^(0x[0-9a-f]*|[0-9]+)$' THEN RETURN 'ip_literal'; END IF;
  IF position('.' IN v_host) = 0 THEN RETURN 'single_label'; END IF;
  FOREACH v_suffix IN ARRAY ARRAY['localhost', 'local', 'localdomain', 'internal', 'intranet', 'lan', 'home', 'corp',
                                  'private', 'test', 'example', 'invalid', 'onion', 'home.arpa'] LOOP
    IF v_host = v_suffix OR right(v_host, char_length(v_suffix) + 1) = '.' || v_suffix THEN RETURN 'local_host'; END IF;
  END LOOP;
  RETURN NULL;
END;
$$;
REVOKE ALL ON FUNCTION public.webhook_url_rejection(TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.webhook_url_rejection(TEXT) TO authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 3. Event payload (shared with the read API): booking facts, never customer personal data
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.api_booking_json(p_booking public.bookings)
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'id', p_booking.id,
    'status', p_booking.status,
    'scheduled_at', p_booking.scheduled_at,
    'duration_minutes', p_booking.duration_minutes,
    'branch_id', p_booking.branch_id,
    'employee_id', p_booking.employee_id,
    'service_id', p_booking.service_id,
    'service_name_en', s.name_en,
    'service_name_ar', s.name_ar,
    'is_home_service', COALESCE(p_booking.is_home_service, FALSE),
    'source', p_booking.source,
    'total_price', p_booking.total_price,
    'tax_amount', p_booking.tax_amount,
    'discount_amount', COALESCE(p_booking.discount_amount, 0),
    'currency', 'SAR',
    'created_at', p_booking.created_at)
  FROM (SELECT 1) one LEFT JOIN public.services s ON s.id = p_booking.service_id;
$$;
REVOKE ALL ON FUNCTION public.api_booking_json(public.bookings) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.api_booking_json(public.bookings) TO service_role;

-- ---------------------------------------------------------------------------
-- 4. Enqueue on booking changes (additive AFTER triggers)
-- ---------------------------------------------------------------------------
-- Delivery is switched on by two platform settings. While either is unset nothing is enqueued, so switching
-- delivery on later does not release a backlog of stale events.
CREATE OR REPLACE FUNCTION public.webhook_delivery_enabled()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.api_setting_int('api.webhook_max_attempts') IS NOT NULL
     AND public.api_setting_int('api.webhook_retry_base_seconds') IS NOT NULL;
$$;
REVOKE ALL ON FUNCTION public.webhook_delivery_enabled() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.webhook_delivery_enabled() TO service_role;

CREATE OR REPLACE FUNCTION public.enqueue_booking_webhooks()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_provider UUID;
  v_types TEXT[] := '{}';
  v_type TEXT;
  v_payload JSONB;
  v_event UUID;
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_types := ARRAY['booking.created'];
    IF NEW.status = 'confirmed' THEN v_types := v_types || 'booking.confirmed'::TEXT; END IF;
  ELSIF NEW.status = 'confirmed' THEN v_types := ARRAY['booking.confirmed'];
  ELSIF NEW.status = 'cancelled' THEN v_types := ARRAY['booking.cancelled'];
  ELSIF NEW.status = 'completed' THEN v_types := ARRAY['booking.completed'];
  END IF;
  IF cardinality(v_types) = 0 OR NOT public.webhook_delivery_enabled() THEN RETURN NEW; END IF;

  SELECT provider_id INTO v_provider FROM public.branches WHERE id = NEW.branch_id;
  IF v_provider IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.webhook_subscriptions s
     WHERE s.provider_id = v_provider AND s.is_active AND s.deleted_at IS NULL
  ) THEN
    RETURN NEW;
  END IF;

  -- An integration feature must never be able to break a booking: a failure here is reported and swallowed.
  BEGIN
    FOREACH v_type IN ARRAY v_types LOOP
      -- Stable per booking and event type: the same transition can only ever produce one event id.
      v_event := md5('primora:booking-event:' || NEW.id::TEXT || ':' || v_type)::UUID;
      v_payload := jsonb_build_object(
        'id', v_event, 'type', v_type, 'api_version', 'v1', 'created_at', now(),
        'data', jsonb_build_object('booking', public.api_booking_json(NEW)));
      INSERT INTO public.webhook_deliveries (subscription_id, provider_id, booking_id, event_id, event_type, payload)
      SELECT s.id, v_provider, NEW.id, v_event, v_type, v_payload
        FROM public.webhook_subscriptions s
       WHERE s.provider_id = v_provider AND s.is_active AND s.deleted_at IS NULL
         AND v_type = ANY (s.event_types)
         AND (s.branch_id IS NULL OR s.branch_id = NEW.branch_id)
      ON CONFLICT (subscription_id, event_id) DO NOTHING;
    END LOOP;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'webhook enqueue failed for booking %: %', NEW.id, SQLERRM;
  END;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.enqueue_booking_webhooks() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trg_webhook_booking_created ON public.bookings;
CREATE TRIGGER trg_webhook_booking_created AFTER INSERT ON public.bookings
  FOR EACH ROW EXECUTE FUNCTION public.enqueue_booking_webhooks();
DROP TRIGGER IF EXISTS trg_webhook_booking_status ON public.bookings;
CREATE TRIGGER trg_webhook_booking_status AFTER UPDATE OF status ON public.bookings
  FOR EACH ROW WHEN (OLD.status IS DISTINCT FROM NEW.status) EXECUTE FUNCTION public.enqueue_booking_webhooks();

-- ---------------------------------------------------------------------------
-- 5. Owner commands
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.create_webhook_endpoint(
  p_provider_id UUID, p_branch_id UUID, p_name TEXT, p_url TEXT, p_event_types TEXT[]
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_name TEXT := btrim(COALESCE(p_name, ''));
  v_reason TEXT;
  v_events TEXT[];
  v_id UUID := gen_random_uuid();
  v_secret TEXT;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Sign in required' USING ERRCODE = '28000'; END IF;
  IF p_provider_id IS NULL OR NOT EXISTS (SELECT 1 FROM public.providers WHERE id = p_provider_id AND owner_id = v_uid) THEN
    RAISE EXCEPTION 'Provider not found' USING ERRCODE = 'P0002';
  END IF;
  IF p_branch_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.branches WHERE id = p_branch_id AND provider_id = p_provider_id) THEN
    RAISE EXCEPTION 'Branch not found' USING ERRCODE = 'P0002';
  END IF;
  IF char_length(v_name) < 3 OR char_length(v_name) > 80 THEN
    RAISE EXCEPTION 'The endpoint needs a name of 3 to 80 characters' USING ERRCODE = '22023';
  END IF;
  v_reason := public.webhook_url_rejection(p_url);
  IF v_reason IS NOT NULL THEN
    RAISE EXCEPTION 'Webhook address not allowed: %', v_reason USING ERRCODE = '22023';
  END IF;
  IF p_event_types IS NULL OR cardinality(p_event_types) = 0 OR EXISTS (SELECT 1 FROM unnest(p_event_types) e WHERE e IS NULL) THEN
    RAISE EXCEPTION 'Choose at least one event' USING ERRCODE = '22023';
  END IF;
  SELECT array_agg(DISTINCT e ORDER BY e) INTO v_events FROM unnest(p_event_types) e;
  IF NOT (v_events <@ ARRAY['booking.created', 'booking.confirmed', 'booking.cancelled', 'booking.completed']::TEXT[]) THEN
    RAISE EXCEPTION 'Unknown event requested' USING ERRCODE = '22023';
  END IF;

  v_secret := 'whsec_' || encode(extensions.gen_random_bytes(32), 'hex');
  BEGIN
    INSERT INTO public.webhook_subscriptions (id, provider_id, branch_id, name, target_url, event_types, is_active, created_by)
    VALUES (v_id, p_provider_id, p_branch_id, v_name, p_url, v_events, TRUE, v_uid);
  EXCEPTION WHEN unique_violation THEN
    RAISE EXCEPTION 'This address is already registered for the provider' USING ERRCODE = '23505';
  END;
  INSERT INTO public.webhook_subscription_secrets (subscription_id, signing_secret) VALUES (v_id, v_secret);

  -- The address can carry a token in its query string, so it is never written to the log.
  PERFORM public.write_audit_log('webhook_endpoint.created', 'webhook_subscriptions', v_id,
    jsonb_build_object('provider_id', p_provider_id, 'branch_id', p_branch_id, 'event_types', to_jsonb(v_events)));
  RETURN jsonb_build_object('id', v_id, 'name', v_name, 'provider_id', p_provider_id, 'branch_id', p_branch_id,
                            'event_types', to_jsonb(v_events), 'signing_secret', v_secret);
END;
$$;
REVOKE ALL ON FUNCTION public.create_webhook_endpoint(UUID, UUID, TEXT, TEXT, TEXT[]) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_webhook_endpoint(UUID, UUID, TEXT, TEXT, TEXT[]) TO authenticated;

CREATE OR REPLACE FUNCTION public.update_webhook_endpoint(p_endpoint_id UUID, p_name TEXT, p_event_types TEXT[])
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_sub public.webhook_subscriptions;
  v_name TEXT := btrim(COALESCE(p_name, ''));
  v_events TEXT[];
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Sign in required' USING ERRCODE = '28000'; END IF;
  SELECT s.* INTO v_sub FROM public.webhook_subscriptions s JOIN public.providers p ON p.id = s.provider_id
   WHERE s.id = p_endpoint_id AND s.deleted_at IS NULL AND p.owner_id = v_uid FOR UPDATE OF s;
  IF NOT FOUND THEN RAISE EXCEPTION 'Webhook endpoint not found' USING ERRCODE = 'P0002'; END IF;
  IF char_length(v_name) < 3 OR char_length(v_name) > 80 THEN
    RAISE EXCEPTION 'The endpoint needs a name of 3 to 80 characters' USING ERRCODE = '22023';
  END IF;
  IF p_event_types IS NULL OR cardinality(p_event_types) = 0 OR EXISTS (SELECT 1 FROM unnest(p_event_types) e WHERE e IS NULL) THEN
    RAISE EXCEPTION 'Choose at least one event' USING ERRCODE = '22023';
  END IF;
  SELECT array_agg(DISTINCT e ORDER BY e) INTO v_events FROM unnest(p_event_types) e;
  IF NOT (v_events <@ ARRAY['booking.created', 'booking.confirmed', 'booking.cancelled', 'booking.completed']::TEXT[]) THEN
    RAISE EXCEPTION 'Unknown event requested' USING ERRCODE = '22023';
  END IF;
  UPDATE public.webhook_subscriptions SET name = v_name, event_types = v_events, updated_at = now() WHERE id = v_sub.id;
  PERFORM public.write_audit_log('webhook_endpoint.updated', 'webhook_subscriptions', v_sub.id,
    jsonb_build_object('provider_id', v_sub.provider_id, 'event_types', to_jsonb(v_events)));
  RETURN jsonb_build_object('id', v_sub.id, 'name', v_name, 'event_types', to_jsonb(v_events));
END;
$$;
REVOKE ALL ON FUNCTION public.update_webhook_endpoint(UUID, TEXT, TEXT[]) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.update_webhook_endpoint(UUID, TEXT, TEXT[]) TO authenticated;

-- Pausing or resuming an endpoint. Pausing drops what is still waiting for it; resuming clears the failure streak.
CREATE OR REPLACE FUNCTION public.set_webhook_endpoint_active(p_endpoint_id UUID, p_active BOOLEAN, p_reason TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_sub public.webhook_subscriptions;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Sign in required' USING ERRCODE = '28000'; END IF;
  IF p_active IS NULL THEN RAISE EXCEPTION 'Say whether the endpoint should be active' USING ERRCODE = '22023'; END IF;
  IF p_reason IS NULL OR char_length(trim(p_reason)) < 3 THEN RAISE EXCEPTION 'A reason is required' USING ERRCODE = '22023'; END IF;
  SELECT s.* INTO v_sub FROM public.webhook_subscriptions s JOIN public.providers p ON p.id = s.provider_id
   WHERE s.id = p_endpoint_id AND s.deleted_at IS NULL AND p.owner_id = v_uid FOR UPDATE OF s;
  IF NOT FOUND THEN RAISE EXCEPTION 'Webhook endpoint not found' USING ERRCODE = 'P0002'; END IF;
  IF v_sub.is_active = p_active THEN
    RETURN jsonb_build_object('id', v_sub.id, 'is_active', v_sub.is_active, 'changed', FALSE);
  END IF;
  IF p_active THEN
    UPDATE public.webhook_subscriptions
       SET is_active = TRUE, disabled_reason = NULL, disabled_at = NULL, consecutive_failures = 0, updated_at = now()
     WHERE id = v_sub.id;
  ELSE
    UPDATE public.webhook_subscriptions
       SET is_active = FALSE, disabled_reason = 'owner', disabled_at = now(), updated_at = now()
     WHERE id = v_sub.id;
    UPDATE public.webhook_deliveries SET status = 'skipped', last_error = 'The endpoint was paused'
     WHERE subscription_id = v_sub.id AND status = 'pending';
  END IF;
  PERFORM public.write_audit_log(CASE WHEN p_active THEN 'webhook_endpoint.resumed' ELSE 'webhook_endpoint.paused' END,
    'webhook_subscriptions', v_sub.id, jsonb_build_object('provider_id', v_sub.provider_id, 'reason', trim(p_reason)));
  RETURN jsonb_build_object('id', v_sub.id, 'is_active', p_active, 'changed', TRUE);
END;
$$;
REVOKE ALL ON FUNCTION public.set_webhook_endpoint_active(UUID, BOOLEAN, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.set_webhook_endpoint_active(UUID, BOOLEAN, TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.rotate_webhook_secret(p_endpoint_id UUID, p_reason TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_sub public.webhook_subscriptions;
  v_secret TEXT;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Sign in required' USING ERRCODE = '28000'; END IF;
  IF p_reason IS NULL OR char_length(trim(p_reason)) < 3 THEN RAISE EXCEPTION 'A reason is required' USING ERRCODE = '22023'; END IF;
  SELECT s.* INTO v_sub FROM public.webhook_subscriptions s JOIN public.providers p ON p.id = s.provider_id
   WHERE s.id = p_endpoint_id AND s.deleted_at IS NULL AND p.owner_id = v_uid FOR UPDATE OF s;
  IF NOT FOUND THEN RAISE EXCEPTION 'Webhook endpoint not found' USING ERRCODE = 'P0002'; END IF;
  v_secret := 'whsec_' || encode(extensions.gen_random_bytes(32), 'hex');
  INSERT INTO public.webhook_subscription_secrets (subscription_id, signing_secret) VALUES (v_sub.id, v_secret)
  ON CONFLICT (subscription_id) DO UPDATE SET signing_secret = EXCLUDED.signing_secret, rotated_at = now();
  PERFORM public.write_audit_log('webhook_endpoint.secret_rotated', 'webhook_subscriptions', v_sub.id,
    jsonb_build_object('provider_id', v_sub.provider_id, 'reason', trim(p_reason)));
  RETURN jsonb_build_object('id', v_sub.id, 'signing_secret', v_secret);
END;
$$;
REVOKE ALL ON FUNCTION public.rotate_webhook_secret(UUID, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rotate_webhook_secret(UUID, TEXT) TO authenticated;

-- Removal is a soft delete: the endpoint disappears from the console and stops receiving events, its secret is
-- destroyed, and its delivery history stays for the audit trail.
CREATE OR REPLACE FUNCTION public.delete_webhook_endpoint(p_endpoint_id UUID, p_reason TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_sub public.webhook_subscriptions;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Sign in required' USING ERRCODE = '28000'; END IF;
  IF p_reason IS NULL OR char_length(trim(p_reason)) < 3 THEN RAISE EXCEPTION 'A reason is required' USING ERRCODE = '22023'; END IF;
  SELECT s.* INTO v_sub FROM public.webhook_subscriptions s JOIN public.providers p ON p.id = s.provider_id
   WHERE s.id = p_endpoint_id AND p.owner_id = v_uid FOR UPDATE OF s;
  IF NOT FOUND THEN RAISE EXCEPTION 'Webhook endpoint not found' USING ERRCODE = 'P0002'; END IF;
  IF v_sub.deleted_at IS NOT NULL THEN
    RETURN jsonb_build_object('id', v_sub.id, 'deleted', TRUE, 'changed', FALSE);
  END IF;
  UPDATE public.webhook_subscriptions
     SET deleted_at = now(), is_active = FALSE, disabled_reason = COALESCE(disabled_reason, 'deleted'),
         disabled_at = COALESCE(disabled_at, now()), updated_at = now()
   WHERE id = v_sub.id;
  DELETE FROM public.webhook_subscription_secrets WHERE subscription_id = v_sub.id;
  UPDATE public.webhook_deliveries SET status = 'skipped', last_error = 'The endpoint was deleted'
   WHERE subscription_id = v_sub.id AND status = 'pending';
  PERFORM public.write_audit_log('webhook_endpoint.deleted', 'webhook_subscriptions', v_sub.id,
    jsonb_build_object('provider_id', v_sub.provider_id, 'reason', trim(p_reason)));
  RETURN jsonb_build_object('id', v_sub.id, 'deleted', TRUE, 'changed', TRUE);
END;
$$;
REVOKE ALL ON FUNCTION public.delete_webhook_endpoint(UUID, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.delete_webhook_endpoint(UUID, TEXT) TO authenticated;

-- Puts a failed or skipped delivery back in the queue with a fresh attempt budget.
CREATE OR REPLACE FUNCTION public.retry_webhook_delivery(p_delivery_id UUID, p_reason TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_delivery public.webhook_deliveries;
  v_sub public.webhook_subscriptions;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Sign in required' USING ERRCODE = '28000'; END IF;
  IF p_reason IS NULL OR char_length(trim(p_reason)) < 3 THEN RAISE EXCEPTION 'A reason is required' USING ERRCODE = '22023'; END IF;
  SELECT d.* INTO v_delivery FROM public.webhook_deliveries d JOIN public.providers p ON p.id = d.provider_id
   WHERE d.id = p_delivery_id AND p.owner_id = v_uid FOR UPDATE OF d;
  IF NOT FOUND THEN RAISE EXCEPTION 'Delivery not found' USING ERRCODE = 'P0002'; END IF;
  IF v_delivery.status = 'pending' THEN
    RETURN jsonb_build_object('id', v_delivery.id, 'status', 'pending', 'changed', FALSE);
  END IF;
  IF v_delivery.status = 'delivered' THEN
    RAISE EXCEPTION 'This event was already delivered' USING ERRCODE = '22023';
  END IF;
  SELECT * INTO v_sub FROM public.webhook_subscriptions WHERE id = v_delivery.subscription_id;
  IF v_sub.deleted_at IS NOT NULL OR NOT v_sub.is_active THEN
    RAISE EXCEPTION 'Resume the endpoint before retrying its deliveries' USING ERRCODE = '22023';
  END IF;
  UPDATE public.webhook_deliveries
     SET status = 'pending', attempt_count = 0, next_attempt_at = now(), last_error = NULL, last_status_code = NULL
   WHERE id = v_delivery.id;
  PERFORM public.write_audit_log('webhook_delivery.retried', 'webhook_deliveries', v_delivery.id,
    jsonb_build_object('provider_id', v_delivery.provider_id, 'reason', trim(p_reason)));
  RETURN jsonb_build_object('id', v_delivery.id, 'status', 'pending', 'changed', TRUE);
END;
$$;
REVOKE ALL ON FUNCTION public.retry_webhook_delivery(UUID, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.retry_webhook_delivery(UUID, TEXT) TO authenticated;

-- ---------------------------------------------------------------------------
-- 6. Delivery state machine (service role only)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.webhook_delivery_settings()
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF COALESCE(auth.jwt() ->> 'role', '') <> 'service_role' THEN
    RAISE EXCEPTION 'Service role required' USING ERRCODE = '42501';
  END IF;
  RETURN jsonb_build_object(
    'enabled', public.webhook_delivery_enabled(),
    'max_attempts', public.api_setting_int('api.webhook_max_attempts'),
    'retry_base_seconds', public.api_setting_int('api.webhook_retry_base_seconds'),
    'disable_after_failures', public.api_setting_int('api.webhook_disable_after_failures'));
END;
$$;
REVOKE ALL ON FUNCTION public.webhook_delivery_settings() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.webhook_delivery_settings() TO service_role;

-- Leases up to p_limit due deliveries to the caller. A leased delivery is not offered again for five minutes, so
-- two workers never send the same event at once; if the worker dies the delivery simply becomes due again.
CREATE OR REPLACE FUNCTION public.webhook_claim_deliveries(p_limit INTEGER DEFAULT 20)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_limit INTEGER := LEAST(GREATEST(COALESCE(p_limit, 20), 1), 200);
  v_result JSONB;
BEGIN
  IF COALESCE(auth.jwt() ->> 'role', '') <> 'service_role' THEN
    RAISE EXCEPTION 'Service role required' USING ERRCODE = '42501';
  END IF;
  IF NOT public.webhook_delivery_enabled() THEN RETURN '[]'::jsonb; END IF;

  WITH due AS (
    SELECT d.id
      FROM public.webhook_deliveries d
      JOIN public.webhook_subscriptions s ON s.id = d.subscription_id
     WHERE d.status = 'pending' AND d.next_attempt_at <= now() AND s.is_active AND s.deleted_at IS NULL
     ORDER BY d.next_attempt_at, d.created_at
     LIMIT v_limit
       FOR UPDATE OF d SKIP LOCKED
  ), leased AS (
    UPDATE public.webhook_deliveries d SET next_attempt_at = now() + interval '5 minutes'
      FROM due WHERE d.id = due.id
    RETURNING d.*
  )
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'delivery_id', l.id, 'subscription_id', l.subscription_id, 'event_id', l.event_id, 'event_type', l.event_type,
           'payload', l.payload, 'attempt_count', l.attempt_count, 'target_url', s.target_url,
           'signing_secret', sec.signing_secret) ORDER BY l.created_at), '[]'::jsonb)
    INTO v_result
    FROM leased l
    JOIN public.webhook_subscriptions s ON s.id = l.subscription_id
    JOIN public.webhook_subscription_secrets sec ON sec.subscription_id = l.subscription_id;
  RETURN v_result;
END;
$$;
REVOKE ALL ON FUNCTION public.webhook_claim_deliveries(INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.webhook_claim_deliveries(INTEGER) TO service_role;

-- Records the outcome of attempt number p_attempt. A report for an attempt that was already recorded (a replay),
-- or for a delivery that is no longer pending, changes nothing.
--   delivered      status = delivered, the endpoint's failure streak resets
--   failed, tries left   status stays pending, next attempt after base * 2^(attempt-1) seconds (at most 24 hours)
--   failed, none left    status = failed
-- Every failed attempt lengthens the endpoint's failure streak; at api.webhook_disable_after_failures the endpoint
-- is switched off and what is still waiting for it is skipped.
CREATE OR REPLACE FUNCTION public.webhook_record_attempt(
  p_delivery_id UUID, p_attempt INTEGER, p_delivered BOOLEAN, p_status_code INTEGER, p_note TEXT
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_delivery public.webhook_deliveries;
  v_max INTEGER := public.api_setting_int('api.webhook_max_attempts');
  v_base INTEGER := public.api_setting_int('api.webhook_retry_base_seconds');
  v_disable_after INTEGER := public.api_setting_int('api.webhook_disable_after_failures');
  v_failures INTEGER;
  v_disabled BOOLEAN := FALSE;
  v_delay NUMERIC;
BEGIN
  IF COALESCE(auth.jwt() ->> 'role', '') <> 'service_role' THEN
    RAISE EXCEPTION 'Service role required' USING ERRCODE = '42501';
  END IF;
  IF p_attempt IS NULL OR p_attempt < 1 OR p_delivered IS NULL THEN
    RAISE EXCEPTION 'An attempt number and an outcome are required' USING ERRCODE = '22023';
  END IF;
  SELECT * INTO v_delivery FROM public.webhook_deliveries WHERE id = p_delivery_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Delivery not found' USING ERRCODE = 'P0002'; END IF;
  IF v_delivery.status <> 'pending' OR v_delivery.attempt_count <> p_attempt - 1 THEN
    RETURN jsonb_build_object('delivery_id', v_delivery.id, 'status', v_delivery.status, 'attempt_count', v_delivery.attempt_count,
                              'next_attempt_at', v_delivery.next_attempt_at, 'endpoint_disabled', FALSE, 'applied', FALSE);
  END IF;
  IF v_max IS NULL OR v_base IS NULL THEN
    RAISE EXCEPTION 'Webhook delivery settings are not set' USING ERRCODE = '55000';
  END IF;

  IF p_delivered THEN
    UPDATE public.webhook_deliveries
       SET status = 'delivered', attempt_count = p_attempt, last_attempt_at = now(), delivered_at = now(),
           last_status_code = p_status_code, last_error = NULL
     WHERE id = v_delivery.id RETURNING * INTO v_delivery;
    UPDATE public.webhook_subscriptions
       SET consecutive_failures = 0, last_success_at = now(), last_attempt_at = now()
     WHERE id = v_delivery.subscription_id;
  ELSE
    IF p_attempt >= v_max THEN
      UPDATE public.webhook_deliveries
         SET status = 'failed', attempt_count = p_attempt, last_attempt_at = now(),
             last_status_code = p_status_code, last_error = left(COALESCE(p_note, ''), 200)
       WHERE id = v_delivery.id RETURNING * INTO v_delivery;
    ELSE
      v_delay := LEAST(v_base::NUMERIC * power(2, LEAST(p_attempt - 1, 30)), 86400);
      UPDATE public.webhook_deliveries
         SET attempt_count = p_attempt, last_attempt_at = now(), next_attempt_at = now() + make_interval(secs => v_delay::DOUBLE PRECISION),
             last_status_code = p_status_code, last_error = left(COALESCE(p_note, ''), 200)
       WHERE id = v_delivery.id RETURNING * INTO v_delivery;
    END IF;
    UPDATE public.webhook_subscriptions
       SET consecutive_failures = consecutive_failures + 1, last_failure_at = now(), last_attempt_at = now()
     WHERE id = v_delivery.subscription_id RETURNING consecutive_failures INTO v_failures;
    IF v_disable_after IS NOT NULL AND v_failures >= v_disable_after THEN
      UPDATE public.webhook_subscriptions
         SET is_active = FALSE, disabled_reason = 'consecutive_failures', disabled_at = now(), updated_at = now()
       WHERE id = v_delivery.subscription_id AND is_active;
      IF FOUND THEN
        v_disabled := TRUE;
        UPDATE public.webhook_deliveries SET status = 'skipped', last_error = 'The endpoint was disabled after repeated failures'
         WHERE subscription_id = v_delivery.subscription_id AND status = 'pending';
        PERFORM public.write_audit_log('webhook_endpoint.auto_disabled', 'webhook_subscriptions', v_delivery.subscription_id,
          jsonb_build_object('provider_id', v_delivery.provider_id, 'consecutive_failures', v_failures));
        SELECT * INTO v_delivery FROM public.webhook_deliveries WHERE id = v_delivery.id;
      END IF;
    END IF;
  END IF;
  RETURN jsonb_build_object('delivery_id', v_delivery.id, 'status', v_delivery.status, 'attempt_count', v_delivery.attempt_count,
                            'next_attempt_at', v_delivery.next_attempt_at, 'endpoint_disabled', v_disabled, 'applied', TRUE);
END;
$$;
REVOKE ALL ON FUNCTION public.webhook_record_attempt(UUID, INTEGER, BOOLEAN, INTEGER, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.webhook_record_attempt(UUID, INTEGER, BOOLEAN, INTEGER, TEXT) TO service_role;

-- ---------------------------------------------------------------------------
-- 7. Administrator audit trigger on every new table
-- ---------------------------------------------------------------------------
SELECT public.attach_admin_audit_trigger('public.webhook_subscription_secrets');
SELECT public.attach_admin_audit_trigger('public.webhook_deliveries');
